=== agarraga/htmlcv/cv.dtd
<!ELEMENT cv (lang, info, works, learns, skills, miscs)>
<!ELEMENT lang (#PCDATA)>
<!ELEMENT info (full_name, dob, address, tlf, email, github, intro)>
<!ELEMENT full_name (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT address (line1, line2)>
<!ELEMENT line1 (#PCDATA)>
<!ELEMENT line2 (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT github (#PCDATA)>
<!ELEMENT intro (#PCDATA)>
<!ELEMENT works (section_title, work+)>
<!ELEMENT section_title (#PCDATA)>
<!ELEMENT work (dates, location, employer, position, description)>
<!ELEMENT dates (start, end)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT employer (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT learns (section_title, learn+)>
<!ELEMENT learn (date, location, institution, title, grade, description)>
<!ELEMENT date (start, end)>
<!ELEMENT institution (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT skills (section_title, skill+)>
<!ELEMENT skill (level, name, specificites, description)>
<!ELEMENT level (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT specificites (#PCDATA)>
<!ELEMENT miscs (section_title, misc+)>
<!ELEMENT misc (name, description)>

=== agarraga/htmlcv/cv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<cv>
  <lang></lang>
  <info>
    <full_name></full_name>
    <dob></dob>
    <address>
      <line1></line1>
      <line2></line2>
    </address>
    <tlf></tlf>
    <email></email>
    <github></github>
    <intro></intro>
  </info>
  <works>
    <section_title></section_title>
    <work>
      <dates>
        <start></start>
        <end></end>
      </dates>
      <location></location>
      <employer></employer>
      <position></position>
      <description></description>
    </work>
  </works>
  <learns>
    <section_title></section_title>
    <learn>
      <date>
        <start></start>
        <end></end>
      </date>
      <location></location>
      <institution></institution>
      <title></title>
      <grade></grade>
      <description></description>
    </learn>
  </learns>
  <skills>
    <section_title></section_title>
    <skill>
      <level></level>
      <name></name>
      <specificites></specificites>
      <description></description>
    </skill>
  </skills>
  <miscs>
    <section_title></section_title>
    <misc>
      <name></name>
      <description></description>
    </misc>
  </miscs>
</cv>
